package it.at7.gemini.conf;

public enum State implements Comparable<State> {
    STARTING,
    STARTED,
    SCHEMA_STORAGE_INITIALIZED,
    SCHEMA_EVENTS_LOADED,
    SCHEMA_RECORDS_INITIALIZED,
    INITIALIZED,
    API_INITIALIZATION,
    API_INITIALIZED,
    GUI_INITIALIZATION,
    GUI_INITIALIZED
}
